basePath: /
definitions:
  go-crud-example_internal_model.User:
    properties:
      age:
        type: integer
      id:
        type: string
      name:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: API сервис для управления пользователями
  title: Users API
  version: "1.0"
paths:
  /users:
    get:
      description: Получить список всех пользователей из базы данных
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/go-crud-example_internal_model.User'
            type: array
      summary: Получить список всех пользователей
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Создать нового пользователя в базе данных
      parameters:
      - description: Данные пользователя
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/go-crud-example_internal_model.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-crud-example_internal_model.User'
      summary: Создать нового пользователя
      tags:
      - users
  /users/{id}:
    delete:
      description: Удалить пользователя из базы данных
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "404":
          description: User not found
          schema:
            type: string
      summary: Удалить пользователя
      tags:
      - users
    get:
      description: Получить данные конкретного пользователя по его ID
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-crud-example_internal_model.User'
        "404":
          description: User not found
          schema:
            type: string
      summary: Получить пользователя по ID
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Обновить данные существующего пользователя
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: string
      - description: Данные пользователя
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/go-crud-example_internal_model.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-crud-example_internal_model.User'
        "404":
          description: User not found
          schema:
            type: string
      summary: Обновить пользователя
      tags:
      - users
swagger: "2.0"
