apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-crud.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "go-crud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "go-crud.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 9090
              name: metrics
          env:
            - name: DB_HOST
              value: {{ .Values.config.database.host }}
            - name: DB_PORT
              value: "{{ .Values.config.database.port }}"
            - name: DB_NAME
              value: {{ .Values.config.database.name }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "go-crud.fullname" . }}
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "go-crud.fullname" . }}
                  key: db-password
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
