apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-crud.fullname" . }}
type: Opaque
data:
  db-user: {{ .Values.config.database.user | b64enc }}
  db-password: {{ .Values.config.database.password | b64enc }}
