apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "go-crud.fullname" . }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: go-crud
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
