apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-crud.fullname" . }}
  labels:
    app: go-crud
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    {{- include "go-crud.selectorLabels" . | nindent 4 }}
